version: '3.4'

services:
  mariadb:
    image: mariadb:10.1
    container_name: my-mariadb
    restart: always
    ports:
      - 3306:3307
    volumes:
      - ./.tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: product
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  my:
    image: jun2org/docker:my
    container_name: my
    ports:
      - 80:80
      - 443:443
      #- 11211:11211
    volumes:
      - .:/htdocs/www
    command: ['./docs/docker/wait_for_it.sh', 'mysqladmin ping -h mariadb -u root -proot', '/usr/bin/supervisord']
    depends_on:
      - mariadb
    links:
      - mariadb
