version: '3.4'

services:
  mariadb:
    image: mariadb:10.1
    container_name: my-mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./.tmp/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: my
      MYSQL_USER: admin
      MYSQL_PASSWORD: test
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
  my:
    image: jun2org/docker:my
    container_name: my
    volumes:
      - ./src:/htdocs/www/src
      - ./docs:/htdocs/www/docs
      - ./enc_secrets.json:/htdocs/www/enc_secrets.json
    ports:
      - 80:80
      - 443:443
      - 11211:11211
    entrypoint: ./docs/docker/entrypoint.sh
    command: ['./docs/docker/wait_for_mariadb.sh', '/usr/bin/supervisord']
    depends_on:
      - mariadb
    links:
      - mariadb
