# Generated by Django 2.0.1 on 2018-05-06 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_book_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbook',
            old_name='reading_status',
            new_name='read_status',
        ),
    ]
