# Generated by Django 2.0.1 on 2018-03-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('title', models.TextField(verbose_name='제목')),
                ('authors', models.TextField(verbose_name='작가들')),
                ('publisher', models.TextField(verbose_name='출판사')),
                ('pub_date', models.DateField(verbose_name='출판일')),
                ('cover_l', models.TextField(verbose_name='커버 Large')),
                ('cover_s', models.TextField(verbose_name='커버 Small')),
                ('description', models.TextField(verbose_name='설명')),
                ('price', models.IntegerField(verbose_name='가격')),
            ],
            options={
                'verbose_name': '책',
                'verbose_name_plural': '첵 리스트',
                'db_table': 'book',
            },
        ),
    ]
