# Generated by Django 2.0.1 on 2018-05-06 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.BigIntegerField(unique=True, verbose_name='ISBN'),
        ),
    ]
