# Generated by Django 2.0.1 on 2018-05-06 10:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('book_app', '0002_auto_20180506_1439'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'verbose_name': 'Book', 'verbose_name_plural': 'Book list'},
        ),
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.TextField(verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_l',
            field=models.TextField(verbose_name='Cover Large'),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_s',
            field=models.TextField(verbose_name='Cover Small'),
        ),
        migrations.AlterField(
            model_name='book',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='book',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='Last modified date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='price',
            field=models.IntegerField(verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='book',
            name='pub_date',
            field=models.DateField(verbose_name='publish date'),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.TextField(verbose_name='publisher'),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.TextField(verbose_name='Title'),
        ),
    ]
