# Generated by Django 2.0.2 on 2018-05-26 13:49

import apps.domains.book.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_app', '0003_auto_20180506_1911'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Create date')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last modified date')),
                ('book_id', models.IntegerField(verbose_name='Book')),
                ('image_type', models.IntegerField(choices=[(0, 'Front cover'), (1, 'Spine'), (2, 'Back cover')], verbose_name='Image type')),
                ('file', models.ImageField(upload_to=apps.domains.book.models.book_image_file_path, verbose_name='Image file')),
                ('source_type', models.IntegerField(choices=[(0, 'Naver'), (1, 'Aladin'), (2, 'Amazon')], verbose_name='Source type')),
                ('source_url', models.TextField(verbose_name='Cover Small')),
            ],
            options={
                'verbose_name': 'Book image',
                'verbose_name_plural': 'Book imgae list',
                'db_table': 'book_image',
            },
        ),
        migrations.RenameField(
            model_name='book',
            old_name='cover_s',
            new_name='cover_url',
        ),
        migrations.RemoveField(
            model_name='book',
            name='cover_l',
        ),
        migrations.AddField(
            model_name='book',
            name='save_cover',
            field=models.BooleanField(default=False, verbose_name='Cover file is saved'),
        ),
        migrations.AddField(
            model_name='book',
            name='back_cover',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_back_cover', to='book_app.BookImage', verbose_name='Back cover image'),
        ),
        migrations.AddField(
            model_name='book',
            name='front_cover',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_front_cover', to='book_app.BookImage', verbose_name='Front cover image'),
        ),
        migrations.AddField(
            model_name='book',
            name='spine',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='book_spine', to='book_app.BookImage', verbose_name='Spine image'),
        ),
    ]
